SMODS.Joker {
    key = "akari",
    rarity = 1,
    cost = 5,
    atlas = 'jonklers',
    blueprint_compat = true,
    pos = { x = 3, y = 6 },
    attributes = { 'chips', 'suit', 'diamonds', 'hearts' },
    pixel_size = { w = 66, h = 90 },
    config = { extra = { mult = 0, mult_gain = 3, chips = 157 } },
    loc_vars = function(self, info_queue, card)
        return {
            vars = { card.ability.extra.chips, card.ability.extra.mult, }
        }
    end,
    calculate = function(self, card, context)
        if context.joker_main then
            local all_light_suits = true
            for _, playing_card in ipairs(G.hand.cards) do
                if not playing_card:is_suit('Hearts', nil, true) and not playing_card:is_suit('Diamonds', nil, true) then
                    all_light_suits = false
                    break
                end
            end
            if all_light_suits then
                return {
                    chips = card.ability.extra.chips
                }
            end
        end
    end,
}


SMODS.Joker {
    key = "cancerous",
    atlas = 'jonklers',
    rarity = 2,
    cost = 6,
    blueprint_compat = false,
    eternal_compat = false,
    pos = { x = 4, y = 6 },
    pools = { ["Meme"] = true, },
    attributes = { 'blindsize', 'generation', 'planet', 'joker' },
    config = { extra = { blindmult = 1 } },
    loc_vars = function(self, info_queue, card)
        info_queue[#info_queue + 1] = G.P_CENTERS.c_pluto
        return { vars = { card.ability.extra.blindmult } }
    end,
    calculate = function(self, card, context)
        if context.setting_blind and not context.blueprint and context.blind.boss and not card.getting_sliced then
            G.GAME.blind.chips = G.GAME.blind.chips + card.ability.extra.blindmult
            G.GAME.blind.chip_text = number_format(G.GAME.blind.chips)
            G.HUD_blind:recalculate()
            G.E_MANAGER:add_event(Event({
                func = function()
                    G.E_MANAGER:add_event(Event({
                        func = function()
                            play_sound("timpani")
                            delay(0.4)
                            return true
                        end,
                    }))
                    return true
                end,
            }))
            return {
                message = "Good Luck!",
                colour = G.C.GREEN,
                message_card = card,
            }
        end
        if context.ante_change and context.ante_end and not context.blueprint then
            local editionname = "e_base"
            if card.edition then
                editionname = card.edition.key
            end
            SMODS.add_card { set = 'Planet', key = "c_pluto", edition = 'e_negative' }
            SMODS.add_card { set = 'Joker', key = "j_neonmod_verycancerous", edition = editionname }
            SMODS.destroy_cards(card, nil, nil, true)
        end
    end
}

SMODS.Joker {
    key = "verycancerous",
    atlas = 'jonklers',
    rarity = 3,
    cost = 6,
    blueprint_compat = false,
    eternal_compat = false,
    pos = { x = 4, y = 6 },
    soul_pos = { x = 5, y = 6 },
    pools = { ["Meme"] = true, },
    attributes = { 'xblindsize', 'generation', 'tag' },
    config = { extra = { blindmult = 3, real = false } },
    loc_vars = function(self, info_queue, card)
        info_queue[#info_queue + 1] = { key = 'tag_polychrome', set = 'Tag' }
        return { vars = { card.ability.extra.blindmult } }
    end,
    calculate = function(self, card, context)
        if context.setting_blind and not context.blueprint and context.blind.boss and not card.getting_sliced then
            card.ability.extra.real = true -- to prevent it from triggering when generated by Cancerous Rodent
            G.GAME.blind.chips = G.GAME.blind.chips * card.ability.extra.blindmult
            G.GAME.blind.chip_text = number_format(G.GAME.blind.chips)
            G.HUD_blind:recalculate()
            G.E_MANAGER:add_event(Event({
                func = function()
                    G.E_MANAGER:add_event(Event({
                        func = function()
                            play_sound("timpani")
                            delay(0.4)
                            return true
                        end,
                    }))
                    return true
                end,
            }))
            return {
                message = "Good Luck!",
                colour = G.C.GREEN,
                message_card = card,
            }
        end
        if context.ante_change and context.ante_end and (card.ability.extra.real == true) and not context.blueprint then
            add_tag({ key = 'tag_polychrome' })
            SMODS.destroy_cards(card, nil, nil, true)
        end
    end,
    in_pool = function(self, args) return false end
}
